Update example to use apiId from requestContext; update aws-sdk-java-core version in pom
rpgreen/apigateway-generic-java-sdk pull request #3
Opened 2017-09-28 12:28 UTC by joshuadfranklin

2017-09-29 00:06 UTC, rpgreen requested changes
Thanks for the PR!

2017-09-29 00:06 UTC, rpgreen commented on examples/simple-sam/src/main/java/ca/ryangreen/examples/Main.java
> +        System.out.println("Response: " + apiIntputStream);
Prefer to remove these lines for simplicity

2017-09-29 00:06 UTC, rpgreen commented on examples/simple-sam/src/main/java/ca/ryangreen/examples/Main.java
> +        System.out.println("Response: " + apiIntputStream);
Prefer to remove this as it's not necessary

2017-09-29 00:06 UTC, rpgreen commented on examples/simple-sam/src/main/java/ca/ryangreen/examples/Main.java
> +        String apiIntputStream = new Scanner(inputStream).useDelimiter("\\A").next();
typo

2017-09-29 00:06 UTC, rpgreen commented on examples/simple-sam/src/main/java/ca/ryangreen/examples/Main.java
> +        JsonNode rootNode = mapper.readTree(apiIntputStream);
Can you inline the variables as they're not used later

2017-09-29 00:06 UTC, rpgreen commented on examples/simple-sam/src/main/java/ca/ryangreen/examples/Main.java
> +        String myApiId = rootNode.path("requestContext").path("apiId").asText();
Can we give this a default value like "TODO" in case this is not called by API Gateway

2017-10-08 18:41 UTC, joshuadfranklin commented
Thanks, I've updated the PR!

2017-10-09 20:35 UTC, rpgreen approved these changes

2017-10-09 20:36 UTC, merged