Added support for (query) parameters
rpgreen/apigateway-generic-java-sdk pull request #4
Opened 2017-11-09 16:14 UTC by raniemi

Perhaps it wasn't necessary for the original use case or maybe an argument could be made that it's still not necessary... regardless, here is a PR that allows for passing parameters/querystrings to the API Gateway.

2017-11-09 23:21 UTC, rpgreen requested changes
Thanks for the PR! Generally looks good, just some minor comments before I can merge

2017-11-09 23:21 UTC, rpgreen commented on src/main/java/ca/ryangreen/apigateway/generic/GenericApiGatewayRequest.java
> +    public Map<String, List<String>> getParameters() {
Let's call this "queryStringParameters" throughout to keep consistent with APIG terminology

2017-11-09 23:21 UTC, rpgreen commented on src/test/java/ca/ryangreen/apigateway/generic/GenericApiGatewayClientTest.java
> +                                && x.getURI().toString().equals(join( ENDPOINT, RESOURCE_PATH, "?key1=value1"))))),
Remove join() and make this explicit

2017-11-09 23:21 UTC, rpgreen commented on src/test/java/ca/ryangreen/apigateway/generic/GenericApiGatewayClientTest.java
>  public class GenericApiGatewayClientTest {
Please ensure we have the following test cases:
+ 0 query params
+ 1 query param
+ > 1 query params
+ query parameters with characters that need to be url encoded

2018-01-31 17:37 UTC, qadir0108 commented
I am passing parameters in GET query string but it is throwing HTTP-400 error.
Can anyone help me? 
https://stackoverflow.com/questions/48548097/calling-aws-api-gateway-issue-with-get-calls

2018-04-02 21:56 UTC, closed without merging